# Generated by Django 6.0 on 2025-12-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.TextField(help_text='Short overview shown on the card')),
                ('details', models.TextField(help_text='Detailed achievements (one per line)')),
                ('tech_stack', models.CharField(help_text='Comma-separated list of technologies', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_current', '-start_date'],
            },
        ),
    ]
