# Generated by Django 6.0 on 2025-12-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_category_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='project',
            name='architecture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('freelance', 'Freelance'), ('startup', 'Startup'), ('open_source', 'Open Source'), ('company', 'Company / Employment')], default='personal', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Programmer', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='video_demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=255),
        ),
    ]
