# Generated by Django 6.0 on 2026-03-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('coop', 'Co-op'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='metrics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=models.TextField(help_text='Achievements — one per line'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated technologies', max_length=255),
        ),
    ]
