# Generated by Django 6.0 on 2026-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_experience_job_type_experience_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('systems', 'Systems'), ('ai_ml', 'AI / ML'), ('web', 'Web'), ('mobile', 'Mobile'), ('devtools', 'Dev Tools'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-date_completed']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='key_features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solution_overview',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='project',
            name='video_demo',
        ),
        migrations.AddField(
            model_name='project',
            name='badge_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='tag_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated', max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
