# Generated by Django 6.0 on 2026-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_project_category_alter_project_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='image',
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('competition', 'Competition'), ('certification', 'Certification'), ('award', 'Award'), ('scholarship', 'Scholarship'), ('honor', 'Honor'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
