# Generated by Django 6.0 on 2026-03-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_pagevisit_remove_achievement_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('progress', models.CharField(choices=[('reading', 'Reading'), ('done', 'Done'), ('up next', 'Up Next')], max_length=40)),
            ],
            options={
                'ordering': ['-progress'],
            },
        ),
    ]
