# Generated by Django 6.0 on 2026-03-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-status']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='progress',
            new_name='status',
        ),
    ]
